# >>> ДОБАВЬТЕ ЭТУ СЕКЦИЮ <<<
[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Backend service for SCB Data Platform" 
authors = ["Andrew Krylov <89921337+andreynes@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "app", from = "."}] 

[tool.poetry.dependencies]
python = ">=3.10"
fastapi = ">=0.115.12,<0.116.0"
uvicorn = {extras = ["standard"], version = ">=0.34.2,<0.35.0"}
pydantic-settings = ">=2.9.1,<3.0.0" 
motor = ">=3.7.1,<4.0.0"
pydantic = {version = "^2.0", extras = ["email"]} 
python-jose = {extras = ["cryptography"], version = "^3.3.0"} 
passlib = {extras = ["bcrypt"], version = "^1.7.4"} 
python-multipart = "*" 

[tool.poetry.group.dev.dependencies]
mongomock-motor = { version = "^0.0.36", python = ">=3.10,<4.0" }
pytest-asyncio = "^0.21.0" 
pytest-mock = "^3.14.1"
# pytest = "^7.0" 
# httpx = "^0.25.0" 

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

