# Dockerfile для финальной диагностики

FROM python:3.10-slim

WORKDIR /app

# Показываем, что находится в контексте сборки
RUN ls -lR .

# Копируем код
COPY backend/app .

# Показываем, что скопировалось
RUN ls -lR .

# Бесконечный сон, чтобы контейнер не падал
CMD sleep infinity