services:
  mongo:
    image: mongo:latest
    container_name: scb_mongo_simple
    ports: ["27017:27017"]
    env_file: [./.env]

  backend:
    container_name: scb_backend_simple
    build:
      context: ../..
      dockerfile: ./infra/docker/backend/Dockerfile.simple
    ports: ["8000:8000"]
    # ЗАКОММЕНТИРУЙТЕ volumes, чтобы проверить чистоту образа
    # volumes: ["../../backend/app:/app"] 
    env_file: [./.env]
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongo