[tool.poetry]
name = "etl"
version = "0.1.0"
description = ""
authors = ["Andrew Krylov <89921337+andreynes@users.noreply.github.com>"] # <--- ИСПРАВЛЕНО ЗДЕСЬ
readme = "README.md"
packages = [  
    { include = "src" }, 
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"

pyyaml = ">=6.0.2,<7.0.0"
python-dotenv = ">=1.1.0,<2.0.0"
pandas = ">=2.2.3,<3.0.0"
openpyxl = ">=3.1.5,<4.0.0"
pdfplumber = ">=0.11.6,<0.12.0"
pymongo = {extras = ["srv"], version = ">=4.3.0,<5.0.0"}
# bson = ">=0.5.10,<0.6.0"
# gridfs = ">=0.5.3,<0.6.0"
clickhouse-connect = { version = "^0.8.17", python = ">=3.8, <4.0" }

[tool.poetry.group.dev.dependencies]
# pytest = "^7.0"
# pytest-mock = "^3.0"
# ruff = "^0.1.0"
# mypy = "^1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"